/*
 * Created on 2020-08-09 ( Time 23:38:02 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package org.philmaster.bootvue.repository;

import org.philmaster.bootvue.model.FormType;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Spring JPA Repository for FormType
 * 
 * @author Telosys Tools Generator
 *
 */
public interface FormTypeRepository extends JpaRepository<FormType, Short> {

}