/*
 * Created on 2020-08-09 ( Time 23:38:02 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.philmaster.bootvue.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "Form"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "Form")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "Form.countAll", query = "SELECT COUNT(x) FROM Form x") })
public class Form extends BaseModel implements Serializable {
	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "name")
	private String name;

	// "formType" (column "formType") is not defined by itself because used as FK in
	// a link

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------
	@ManyToOne
	private FormType formType;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public Form() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : name ( )
	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------
	public void setFormType(FormType formType) {
		this.formType = formType;
	}

	public FormType getFormType() {
		return this.formType;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append(this.getId());
		sb.append("]:");
		sb.append(name);
		return sb.toString();
	}

}